<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"会员管理",
			            "menuJump":"列表",
			            "tableName":"huiyuan"
			        }
			    ],
			    "menu":"会员管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出口基地管理",
                        "menuJump":"列表",
                        "tableName":"cukoujidi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"出口基地留言管理",
                        "menuJump":"列表",
                        "tableName":"cukoujidiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"出口基地收藏管理",
                        "menuJump":"列表",
                        "tableName":"cukoujidiCollection"
                    }
                ],
                "menu":"出口基地管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基地产品管理",
                        "menuJump":"列表",
                        "tableName":"jidichanpin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"基地产品留言管理",
                        "menuJump":"列表",
                        "tableName":"jidichanpinLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"基地产品收藏管理",
                        "menuJump":"列表",
                        "tableName":"jidichanpinCollection"
                    }
                ],
                "menu":"基地产品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基地企业管理",
                        "menuJump":"列表",
                        "tableName":"jidiqiye"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基地企业留言管理",
                        "menuJump":"列表",
                        "tableName":"jidiqiyeLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"基地企业收藏管理",
                        "menuJump":"列表",
                        "tableName":"jidiqiyeCollection"
                    }
                ],
                "menu":"基地企业管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"政策法规管理",
                        "menuJump":"列表",
                        "tableName":"zhengchefagui"
                    }
                ],
                "menu":"政策法规管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"资讯动态管理",
                        "menuJump":"列表",
                        "tableName":"zhixundongtai"
                    }
                ],
                "menu":"资讯动态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"会员专区管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"会员专区管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJidichanpin"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"企业类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJidiqiye"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"政策法规类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhengchefagui"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"资讯动态类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhixundongtai"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	
	{
	    "backMenu":[
			{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"出口基地管理",
	                    "menuJump":"列表",
	                    "tableName":"cukoujidi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"出口基地留言管理",
	                    "menuJump":"列表",
	                    "tableName":"cukoujidiLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"出口基地收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"cukoujidiCollection"
	                }
	            ],
	            "menu":"出口基地管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"基地产品管理",
	                    "menuJump":"列表",
	                    "tableName":"jidichanpin"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"基地产品留言管理",
	                    "menuJump":"列表",
	                    "tableName":"jidichanpinLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"基地产品收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jidichanpinCollection"
	                }
	            ],
	            "menu":"基地产品管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"基地企业管理",
	                    "menuJump":"列表",
	                    "tableName":"jidiqiye"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"基地企业留言管理",
	                    "menuJump":"列表",
	                    "tableName":"jidiqiyeLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"基地企业收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jidiqiyeCollection"
	                }
	            ],
	            "menu":"基地企业管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"政策法规管理",
	                    "menuJump":"列表",
	                    "tableName":"zhengchefagui"
	                }
	            ],
	            "menu":"政策法规管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资讯动态管理",
	                    "menuJump":"列表",
	                    "tableName":"zhixundongtai"
	                }
	            ],
	            "menu":"资讯动态管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"会员专区管理",
	                    "menuJump":"列表",
	                    "tableName":"forum"
	                }
	            ],
	            "menu":"会员专区管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"会员",
	    "tableName":"yonghu"
	}
	,
	
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出口基地管理",
	                    "menuJump":"列表",
	                    "tableName":"cukoujidi"
	                }
	            ],
	            "menu":"出口基地管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"基地产品管理",
	                    "menuJump":"列表",
	                    "tableName":"jidichanpin"
	                }
	            ],
	            "menu":"基地产品管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"基地企业管理",
	                    "menuJump":"列表",
	                    "tableName":"jidiqiye"
	                }
	                
	            ],
	            "menu":"基地企业管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"政策法规管理",
	                    "menuJump":"列表",
	                    "tableName":"zhengchefagui"
	                }
	            ],
	            "menu":"政策法规管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"资讯动态管理",
	                    "menuJump":"列表",
	                    "tableName":"zhixundongtai"
	                }
	            ],
	            "menu":"资讯动态管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
